ordernow/config/routes.rb
Rails.application.routes.draw do
  get 'welcome/index'
  root 'welcome#index'

  resources :orders
  get 'deliver/:id ', :to => 'orders#deliver', :as => :deliver
  get 'next', :to => 'orders#tomorrow_order'
  get 'back', :to => 'orders#yesterday_order'
  get 'today', :to => 'orders#today_order'
end

ordernow/app/models/order.rb
class Order < ActiveRecord::Base
    validates :data, :description, :value, presence:  { message: ' - Esse campo é obrigatorio' }
    validates :value, numericality: { greater_than_or_equal_to: 1, message: ' - O valor tem de ser maior que zero' }
end

ordernow/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

ordernow/app/controllers/orders_controller.rb
class OrdersController < ApplicationController

    $request_date = Date.today

    def index
        @orders = Order.where(data: $request_date)
    end

    def new
        @orders = Order.new
    end

    def create
        @orders = Order.new(orders_params)
        if @orders.save
            $request_date = @orders.data
            redirect_to orders_path
        else
          render :new
        end
    end

    def show
        @orders = Order.find(params[:id])
    end

    def edit
        @orders = Order.find(params[:id])
    end

    def update
        @orders = Order.find(params[:id])
        if @orders.update(orders_params)
            $request_date = @orders.data
            redirect_to @orders
        else
          render :edit
        end
    end

    def destroy
        @orders = Order.find(params[:id])
        @orders.destroy
        redirect_to orders_path
    end

    def deliver
        @orders = Order.find(params[:id])
        if @orders.deliver == false
            @orders.deliver = true
            @orders.save
            redirect_to action: "index"
        else
        end
    end

    def tomorrow_order
        $request_date += 1.day
        redirect_to orders_path
    end

    def yesterday_order
        $request_date -= 1.day
        redirect_to orders_path
    end

    def today_order
        $request_date = Date.today
        redirect_to orders_path
    end

    private
        def orders_params
            params.require(:order).permit(:data, :description, :value)
        end
    

end

ordernow/app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
  end
end

ordernow/app/helpers/application_helper.rb
module ApplicationHelper
end

ordernow/app/helpers/orders_helper.rb
module OrdersHelper
end

ordernow/app/helpers/welcome_helper.rb
module WelcomeHelper
end

ordernow/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Ordernow</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

ordernow/app/views/orders/edit.html.erb
<!DOCTYPE html>
<html lang="pt-br" dir="ltr">
    <head>
        <meta charset="utf-8">
        <title>Edit</title>
        <%= stylesheet_link_tag "custom.css" %>
        <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.5.0/css/all.css" integrity="sha384-B4dIYHKNBt8Bc12p+WXckhzcICo0wtJAoU8YZTY5qE0Id1GSseTk6S+L3BlXeVIU" crossorigin="anonymous">
    </head>
    <body>
        <div class="container">

            <%= link_to '<i class="fas fa-angle-left _icon"></i>'.html_safe, orders_path %>
            <div class="row">
                <div class="col-sm-12 col-md-10 col-lg-12 _center">
                    <%= form_for @orders, url: {action: "update"} do |f| %>
                        <h2>Date</h2>
                        <%= f.date_field :data, as: :date, value: f.object.data %>
                        <h2>Description</h2>
                        <%= f.text_field :description %>
                        <h2>Value</h2>
                        <%= f.number_field :value %>
                        <%= f.submit "Edit" ,class: 'btn' %>
                    <% end %>

                    <% if @orders.errors.any? %>
                        <div id="error_explanation">
                            <h2><%= pluralize(@orders.errors.count, "error") %> impedindo esse pedido de ser criado: </h2>
                            <ul>
                                <% @orders.errors.full_messages.each do |msg| %>
                                    <li><%= msg %></li>
                                <% end %>
                            </ul>
                        </div>
                    <% end %>
                </div>
            </div>
        </div>
    </body>
</html>

ordernow/app/views/orders/index.html.erb
<!DOCTYPE html>
<html lang="pt-br" dir="ltr">
    <head>
        <meta charset="utf-8">
        <title>Orders</title>
        <%= stylesheet_link_tag "custom.css" %>
        <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.5.0/css/all.css" integrity="sha384-B4dIYHKNBt8Bc12p+WXckhzcICo0wtJAoU8YZTY5qE0Id1GSseTk6S+L3BlXeVIU" crossorigin="anonymous">
    </head>
    <body>

        <div class="container">
            <h1>
                Order list
                <%= link_to '<i class="fas fa-plus-circle _icon"></i>'.html_safe, new_order_path %>
            </h1>
            <p>
                Day <%= $request_date.try(:strftime,"%d") %>
                Month <%= $request_date.try(:strftime,"%m") %>
            </p>
            <% if !@orders.blank? %>
                <div class="row">
                    <div class="col-sm-12 col-md-10 col-lg-12">
                        <div class="table-responsive">
                            <table class="table">
                                <tr>
                                    <th>Date</th>
                                    <th>Nº</th>
                                    <th>Description</th>
                                    <th>Value</th>
                                    <th>Show</th>
                                    <th>Edit</th>
                                    <th>Destroy</th>
                                    <th>Deliver</th>
                                </tr>
                                <% @orders.each do |order| %>
                                <tr>
                                    <td><%= order.data.try(:strftime,"%d/%m/%Y") %></td>
                                    <td><%= order.id %></td>
                                    <td><%= order.description %></td>
                                    <td>R$ <%= order.value %></td>

                                    <td style=text-align:center><%= link_to '<i class="fas fa-eye _icon"></i>'.html_safe, order_path(order) %></td>
                                    <td style=text-align:center><%= link_to '<i class="fas fa-edit _icon"></i>'.html_safe, edit_order_path(order) %></td>
                                    <td style=text-align:center><%= link_to '<i class="fas fa-trash-alt _icon"></i>'.html_safe, order_path(order),method: :delete,data: { confirm: 'Are you sure?' } %></td>

                                    <% if (order.deliver) %>
                                        <td style=text-align:center><i class="fas fa-check _icon"></i></td>

                                    <% else %>
                                        <td style=text-align:center><%= link_to '<i class="fas fa-truck _icon"></i>'.html_safe, deliver_path(order) %></td>
                                    <% end %>
                                </tr>
                                <% end %>
                            </table>
                        </div>
                    </div>
                <% else %>
                    <div class="no_data">
                        There's no order for this date.
                    </div>
                <% end %>
                <div class="col-sm-12 col-md-12 col-lg-12">
                    <div style=text-align:center>
                        <%= link_to '<i class="fas fa-angle-left _icon"></i>'.html_safe, back_path %>
                        <%= link_to '<i class="fas fa-home _icon"></i>'.html_safe, today_path %>
                        <%= link_to '<i class="fas fa-angle-right _icon"></i>'.html_safe, next_path %>
                    </div>

                </div>
            </div>

        </div>

    </body>
</html>

ordernow/app/views/orders/new.html.erb
<!DOCTYPE html>
<html lang="pt-br" dir="ltr">

    <head>
        <meta charset="utf-8">
        <title>New Order</title>
        <%= stylesheet_link_tag "custom.css" %>
        <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.5.0/css/all.css" integrity="sha384-B4dIYHKNBt8Bc12p+WXckhzcICo0wtJAoU8YZTY5qE0Id1GSseTk6S+L3BlXeVIU" crossorigin="anonymous">
    </head>

    <body>

        <div class="container">
            <%= link_to '<i class="fas fa-angle-left _icon"></i>'.html_safe, orders_path %>
            <div class="row">
                <div class="col-sm-12 col-md-10 col-lg-12 _center">
                    <%= form_for @orders, url: {action: "create"} do |f| %>
                        <h2>Date</h2>
                        <%= date_field(:order, :data) %>
                        <h2>Description</h2>
                        <%= f.text_field :description %>
                        <h2>Value</h2>
                        <%= f.number_field :value %>
                        <%= f.submit "Create" ,class: 'btn' %>
                    <% end %>

                    <% if @orders.errors.any? %>
                        <div id="error_explanation">
                            <h2><%= pluralize(@orders.errors.count, "error") %> impedindo esse pedido de ser criado: </h2>
                            <ul>
                                <% @orders.errors.full_messages.each do |msg| %>
                                    <li><%= msg %></li>
                                <% end %>
                            </ul>
                        </div>
                    <% end %>
                </div>
            </div>
        </div>

    </body>
</html>

ordernow/app/views/orders/show.html.erb
<!DOCTYPE html>
<html lang="pt-br" dir="ltr">
    <head>
        <meta charset="utf-8">
        <title>Order Details</title>
        <%= stylesheet_link_tag "custom.css" %>
        <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.5.0/css/all.css" integrity="sha384-B4dIYHKNBt8Bc12p+WXckhzcICo0wtJAoU8YZTY5qE0Id1GSseTk6S+L3BlXeVIU" crossorigin="anonymous">
    </head>
    <body>

        <div class="container">
            <%= link_to '<i class="fas fa-angle-left _icon"></i>'.html_safe, orders_path %>
            <div class="row">
                <div class="col-sm-12 col-md-10 col-lg-12 _center">
                    <p>
                        <strong>Date:</strong>
                        <%= @orders.data %>
                    </p>
                    <p>
                        <strong>Description:</strong>
                        <%= @orders.description %>
                    </p>
                    <p>
                        <strong>Value:</strong>
                        <%= @orders.value %>
                    </p>
                </div>
            </div>
        </div>

    </body>
</html>

ordernow/app/views/welcome/index.html.erb
<!DOCTYPE html>
<html lang="pt-br" dir="ltr">
    <head>
        <meta charset="utf-8">
        <title>Edit</title>
        <%= stylesheet_link_tag "custom.css" %>
        <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.5.0/css/all.css" integrity="sha384-B4dIYHKNBt8Bc12p+WXckhzcICo0wtJAoU8YZTY5qE0Id1GSseTk6S+L3BlXeVIU" crossorigin="anonymous">
    </head>
    <body>
        <div class="container">

            <%= link_to '<i class="fas fa-angle-right _icon"></i>'.html_safe, controller: 'orders' %>

            <div class="row">
                <div class="descricao">
                <p style=text-align:justify;>
                    <h1>Desenvolvimento Web II</h1>
                    <hr>
                    O presente trabalho foi desenvolvido como parte da
                    disciplina de Desenvolvimento Web II do curso de Sistemas
                    de informação da UniRedentor.
                    <br>
                    <h2>Nota ao professor:</h2>
                    <br>
                    Tal trabalho utiliza o bootstrap instalado por meio de 'gems'
                    e o Bundle e a biblioteca <a href="https://fontawesome.com/">fontawesome</a>
                    servida por CDN, logo, é recomendado ter conexão estabelecida
                    com a internet para que a experiencia com a interface seja
                    completa.
                    <br>
                    <br>
                    Otávio Reis Perkles -1701299 - UniRedentor2018


                </p>
                </div>
            </div>
        </div>
    </body>
</html>